;
; This code is automatically generated by the FormDesigner.
; Manual modification is possible to adjust existing commands, but anything else will be dropped when the code is compiled.
; Event procedures needs to be put in another source file.
;

Global Window_0, t

Global Window_0_Date_0, Window_0_Text_0, Window_0_Date_1, Window_0_Text_2, Window_0_Text_3, Window_0_Button_0,
       Window_0_Frame_0, Window_0_Text_4, Window_0_Text_5, Window_0_Text_6, Window_0_Text_7, Window_0_Text_8


Procedure OpenWindow_0(x = 0, y = 0, width = 215, height = 160)
  Window_0 = OpenWindow(#PB_Any, x, y, width, height, "Расчет кафарата от закаата", #PB_Window_SystemMenu | #PB_Window_ScreenCentered)                                                                                                           
  Window_0_Date_0 = DateGadget(#PB_Any, 5, 25, 101, 26, "06.11.2017")                                                                                                                                
  Window_0_Text_0 = TextGadget(#PB_Any, 5, 5, 101, 16, "Начало периода")
  Window_0_Date_1 = DateGadget(#PB_Any, 110, 25, 101, 26, "06.11.2017")                                                                                                                                    
  Window_0_Text_2 = TextGadget(#PB_Any, 110, 5, 101, 16, "Конец периода")
  Window_0_Text_3 = TextGadget(#PB_Any, 10, 75, 126, 16, "Количество в муддах:")                 
  Window_0_Button_0 = ButtonGadget(#PB_Any, 5, 130, 206, 26, "Расчитать")
  Window_0_Frame_0 = FrameGadget(#PB_Any, 5, 55, 206, 71, "Результат по формуле (A=15*n(n+1))")
  Window_0_Text_4 = TextGadget(#PB_Any, 10, 90, 121, 16, "Количество в тоннах:")
  Window_0_Text_5 = TextGadget(#PB_Any, 140, 75, 66, 16, "0", #PB_Text_Right)                                                           
  Window_0_Text_6 = TextGadget(#PB_Any, 140, 90, 66, 16, "0", #PB_Text_Right)                                                           
  Window_0_Text_7 = TextGadget(#PB_Any, 10, 105, 121, 16, "Количество в рублях:")                                                                               
  Window_0_Text_8 = TextGadget(#PB_Any, 140, 105, 66, 16, "0", #PB_Text_Right)                                                                                                                                      
EndProcedure

Procedure Window_0_Events(Event)
  Select Event
    Case #PB_Event_CloseWindow
      ProcedureReturn #False
      
    Case #PB_Event_Menu
      Select EventMenu()
      EndSelect
      
    Case #PB_Event_Gadget
      Select EventGadget()
        Case Window_0_Date_0, Window_0_Date_1
          Select EventType()
            Case #PB_EventType_Change
              SetGadgetState(EventGadget(), GetGadgetState(EventGadget()))
              
          EndSelect
          
        Case Window_0_Button_0
          t = Val(StringField(GetGadgetText(Window_0_Date_1), 3, ".")) 
          t - (Val(StringField(GetGadgetText(Window_0_Date_0), 3, "."))+14.5)
          t = (t+(t*11)/354)
          m = 15*t*(t+1)
          
          SetGadgetText(Window_0_Text_5, Str(m))
          SetGadgetText(Window_0_Text_6, Str(m*544))
          SetGadgetText(Window_0_Text_8, Str((m*544)*7000))
      EndSelect
  EndSelect
  
  ProcedureReturn Window_0
EndProcedure

;- Выполнение
CompilerIf #PB_Compiler_IsMainFile
  OpenWindow_0()
  While IsWindow(Window_0_Events( WaitWindowEvent())) : Wend
CompilerEndIf
