;
; This code is automatically generated by the FormDesigner.
; Manual modification is possible to adjust existing commands, but anything else will be dropped when the code is compiled.
; Event procedures needs to be put in another source file.
;

Global Window_0

Global Date_0, Text_0, Date_1, Text_2, Text_3, Button_0


Procedure OpenWindow_0(x = 0, y = 0, width = 445, height = 300)
  Window_0 = OpenWindow(#PB_Any, x, y, width, height, "", #PB_Window_SystemMenu|#PB_Window_ScreenCentered)                                                                               
  Date_0 = DateGadget(#PB_Any, 5, 35, 151, 26, "06.11.2017")                                                  
  Text_0 = TextGadget(#PB_Any, 5, 5, 151, 26, "Начало периода")                                                 
  Date_1 = DateGadget(#PB_Any, 165, 35, 151, 26, "06.11.2017")                                                   
  Text_2 = TextGadget(#PB_Any, 165, 5, 151, 26, "Конец периода")                                                  
  Text_3 = TextGadget(#PB_Any, 325, 5, 116, 26, "Количество мудд", #PB_Text_Center)                                                  
  Button_0 = ButtonGadget(#PB_Any, 325, 35, 116, 26, "Получить")                                                       
EndProcedure

Procedure Window_0_Events(Event)
  Select Event
    Case #PB_Event_CloseWindow
      ProcedureReturn #False

    Case #PB_Event_Menu
      Select EventMenu()
      EndSelect

    Case #PB_Event_Gadget
      Select EventGadget()
      EndSelect
  EndSelect
  
  ProcedureReturn Window_0
EndProcedure

OpenWindow_0()
While IsWindow(Window_0_Events( WaitWindowEvent())) : Wend